# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: vi
pipeline:
- name: "components.pyvi_tokenizer.PyviTokenizer"
- name: "components.bert_vector_feature.BertVectorsFeaturizer"
- name: "EmbeddingIntentClassifier"


# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: MemoizationPolicy
  - name: KerasPolicy
  - name: MappingPolicy
