# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: vi
pipeline:
- name: "components.tokenizer.MyTokenizer"
- name: "components.xlnet_bert_nlu.XlnetBertNLU"
- name: "components.entity_synonym.EntitySynonymMapper"

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: MemoizationPolicy
  - name: KerasPolicy
  - name: MappingPolicy
